[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v5.0.0"
hooks = [
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-merge-conflict" },
]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "eslint"
name = "eslint"
language = "system"
entry = "bun eslint --fix"
types_or = ["ts", "tsx", "javascript", "jsx"]

[[repos.hooks]]
id = "prettier"
name = "prettier"
language = "system"
entry = "bun prettier --write --ignore-unknown"
types_or = ["ts", "tsx", "javascript", "jsx", "json", "css", "markdown", "yaml"]


[[repos.hooks]]
id = "tsc compile"
name = "tsc compile"
language = "system"
entry = "bun run typecheck"
pass_filenames = false
types_or = ["ts", "tsx"]
